### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="pic01.jpg"
Content-Type: application/octet-stream

< D:/temp/upload/pic01.jpg

### 查询媒资信息
POST {{media_host}}/media/files?pageNo=1&pageSize=10
Content-Type: application/json

{
  "filename": "1",
  "fileType": "001002",
  "auditStatus":"002003"
}